### ISSUE TITLE
C++/CLI syntax highlighting messed up by attributes.

### ISSUE THREAD

**Issue by sonicfly** [jeff-hykin/better-cpp-syntax#607]
Checklist

- [X] This problem exists even with the setting `"C_Cpp.enhancedColorization": "Disabled"`

## The code with a problem is:
```
	[LinuxExcluded]
	[Description("For testing")]
	public ref class TestClass
	...
```

## It looks like:
![Screen Shot 2022-10-13 at 13 50 49](https://user-images.githubusercontent.com/458466/195707905-de1eff57-6b5a-4dbf-a689-8488b68f585d.png)
![Screen Shot 2022-10-13 at 13 51 50](https://user-images.githubusercontent.com/458466/195708357-093f45d1-4b0b-4e7b-bbe2-b1a7c7b98772.png)

## It should look like:
It should looks like the second screenshot.
Seems the C++/CLI attributes will mess up the quotation detection and everything becomes red color after. And also single attribute seems OK (as the second screenshot shows).
This issue doesn't happen if I disable the better-cpp-syntax plugin, but irrelevant to C_Cpp.enhancedColorization setting.
And this issue shows up recently, not sure it is caused by VSCode or better-cpp-syntax plugin update, but I don't remember having this issue before.

**Comment by jeff-hykin** [comment]
Thats strange if its a recent change, but disabling the extension means it probably is. 
The color issue is happening because `[LinuxExcluded]` looks like the start of a lambda. 

I didn't know attributes could start with only a single bracket. Is there a link to the specification so I can make sure to cover all the syntax cases? Something like: 

<img width="882" alt="Screen Shot 2022-10-27 at 6 00 14 PM" src="https://user-images.githubusercontent.com/17692058/198413524-5521a0ae-04da-4ff5-994f-1ca94e42efec.png">

**Comment by jeff-hykin** [comment]
(not fixed but also I never found a reference to single-bracket attributes)
