### ISSUE TITLE
Closing bracket scope reported as "source.cpp" when preceded by a #endif

### ISSUE THREAD

**Issue by guiherzog** [jeff-hykin/better-cpp-syntax#616]
Checklist

- [x] This problem exists even with the setting `"C_Cpp.enhancedColorization": "Disabled"`

## The code with a problem is:
```
if (1 === 1) {
    #ifdef DIRECTIVE
    
    #endif
} // <- the scope of this bracket is only "source.cpp"
```

## It looks like:
The closing bracket scope is `source.cpp`.
![Screen Shot 2022-11-30 at 17 05 39](https://user-images.githubusercontent.com/3836025/204848385-53d57721-2b96-456d-a032-6b5d85e025dc.png)

This seem to happen due to this line: https://github.com/jeff-hykin/better-cpp-syntax/blob/master/syntaxes/cpp.tmLanguage.json#L558

I don't have a lot of experience with Textmate grammars, but I am wondering why the second part of the regex is needed there.\
`(?=\s*#\s*(?:elif|else|endif)\b)`
They seem to have some weird matches on: https://regex101.com/r/Xhdau3/1 and I don't see how those #endif directives can close a block? Could you help me understand what's the issue?

## It should look like:
The closing bracket scope should be: 
punctuation.section.block.end.bracket.curly.cpp
meta.block.cpp
source.cpp

This is correct if I remove the second part of the regex:
![image](https://user-images.githubusercontent.com/3836025/204850790-1e7778f6-c66e-489e-a7b7-85216b8d2f9b.png)

**Comment by jeff-hykin** [comment]
>  don't see how those #endif directives can close a block?

You and me both. The only time things should get chomped like that are if a `while` was used, or if there was an inline pattern that first matches a chunk of text then internally includes a pattern-range on that one-line-or-less match (the pattern range will not ever exceed the one-line-or-less chunk). However neither of those are the case here. Makes me wonder if its actually an issue with the implementation of Textmate.

Anyways, while I was busy being baffeled by that I found some other issues with the preprocessor patterns, specifically the one you mentioned. Your case was fixed, but other test cases were failing.

I removed all the `endif` patterns entirely and the behavior was still happening. For some horrible unknown the `{}` pattern was actually checking for endif's and was ending itself early. That chunk was from some really old legacy code from before this repository.

That said, now the actual issue is fixed on `v1.17.2`
